### ISSUE TITLE
false duplicate result with short args

### ISSUE THREAD

**Issue by qfroemke** [Qartar/qflags#3]
It looks like the short-argument name ability supports having multi-character values (like -st for example). However, when the parser attempts to add add the short-argument it falsely determines that a multi-character arg equals one of different lengths. For example, if I have two short args with values of:

-s
-st

the parser thinks these are equal. It looks like this is due to the std::equal compare using the min size of the two arguments.

**Comment by Qartar** [comment]
Hi there! Multi-character values for short argument names are allowed in order to support multibyte UTF-8 characters; it's not really intended to handle short names of arbitrary length. There is no logic during parsing to disambiguate `st` from `s` followed by `t` (since flags can be grouped, e.g. `-a -b` is equivalent to `-ab`) so the warning you're seeing is legitimate but maybe could be reworded for clarity. Does that make sense?

**Comment by qfroemke** [comment]
Gotcha. That makes sense, especially with being able to group flags together. Thanks!
